version: 0.0
os: linux
files:
  - source: /
    destination: /opt/hello_erlang
hooks:
  ApplicationStop:
    - location: config/aws/codedeploy/stop_application.sh
      timeout: 60
      runas: ec2-user
  BeforeInstall:
    - location: config/aws/codedeploy/before_install.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: config/aws/codedeploy/after_install.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: config/aws/codedeploy/start_application.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: config/aws/codedeploy/validate_service.sh
      timeout: 60
      runas: ec2-user
